drop table if exists album CASCADE;
drop table if exists album_genre CASCADE;
drop table if exists artist CASCADE;
drop table if exists genre CASCADE;
drop table if exists playlist CASCADE;
drop table if exists playlist_tracks CASCADE;
drop table if exists track CASCADE;
drop table if exists track_contributing_artists CASCADE;
drop table if exists user CASCADE;
create table album (
    id integer generated by default as identity,
    cover longtext not null,
    name varchar(100) not null,
    artist_id integer,
    primary key (id)
);
create table album_genre (
    albums_id integer not null,
    genre_id integer not null
);
create table artist (
    id integer generated by default as identity,
    name varchar(100) not null,
    primary key (id)
);
create table genre (
    id integer generated by default as identity,
    description varchar(250) not null,
    name varchar(100) not null,
    primary key (id)
);
create table playlist (
    id integer generated by default as identity,
    artwork longtext not null,
    description varchar(500) not null,
    name varchar(100) not null,
    primary key (id)
);
create table playlist_tracks (
    playlists_id integer not null,
    tracks_id integer not null
);
create table track (
    id integer generated by default as identity,
    duration integer,
    lyrics varchar(255),
    name varchar(100) not null,
    album_id integer,
    artist_id integer,
    primary key (id)
);
create table track_contributing_artists (
    track_id integer not null,
    artist_id integer not null
);
create table user (
    id integer generated by default as identity,
    password varchar(255),
    roles varchar(255),
    username varchar(255),
    primary key (id)
);
alter table album
add constraint FKmwc4fyyxb6tfi0qba26gcf8s1 foreign key (artist_id) references artist on delete cascade;
alter table album_genre
add constraint FKld60pu9t8ff70bc6nrnnv91lx foreign key (genre_id) references genre on delete cascade;
alter table album_genre
add constraint FK5ld7h3hc4ofcktaovx6isvgsl foreign key (albums_id) references album;
alter table playlist_tracks
add constraint FKs1ti0pm4ttt0lkx5xi86iwxcb foreign key (tracks_id) references track on delete cascade;
alter table playlist_tracks
add constraint FKknn707j3xwuyvqmpd8v8s5k2d foreign key (playlists_id) references playlist;
alter table track
add constraint FKaxm9pbgk7ptorfyk3o6911q05 foreign key (album_id) references album on delete cascade;
alter table track
add constraint FKi28jadqiuqk1dlxtl0me7hqh2 foreign key (artist_id) references artist;
alter table track_contributing_artists
add constraint FK5qskhoyxnsu0h65u1g8k5vk7i foreign key (artist_id) references artist on delete cascade;
alter table track_contributing_artists
add constraint FKo7h16q4wo71551jdkqc4eqmvv foreign key (track_id) references track on delete cascade;